version: '3.8'

services:
  conectaroca:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
volumes:
  db_data:
